[connections.jobhunting]
    type="sql"
    dialect="mysql"
    username="YOUR_USERNAME_HERE"
    password="YOUR_PASSWORD_HERE"
    host="localhost" # IP or URL
    port=3306 # Port number
    database="jobhunting" # Database name

[openai]
    api_key="YOUR_API_KEY_HERE"
    base_url="https://api.openai.com"